#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 30 18:25:30 2017

@author: gustafehn
"""
import numpy as np
import scipy.special as sps
import matplotlib.pyplot as plt
from numba import jit
import time

#
start = time.time()
M=26
L=100
K=10*L
t_pos=np.linspace(0,1,L)
t_neg=np.linspace(-10,0,10*L)
t=np.union1d(t_neg,t_pos)

def Hurst(x,letter):
    case=letter%6
    if case==0:
        return 0.1*np.sin(2*np.pi*x*letter/6)+.5
    elif case==1:
        return .2/(1+np.exp(-550.*(x-.1667*(letter+5)/6)))+.4
    elif case==2:
        return 0.6-(.2/(1+np.exp(-550.*(x-(.1667*(letter+4)/6)))))
    elif case==3:
        return -0.1*np.sin(2*np.pi*x*((letter+3)/6))+.5
    elif case==4:
        c=int(letter/M*L)
        x_out=np.zeros(np.size(x))
        x_out[:c]=-0.2*x[:c]/(letter/M)+.6
        x_out[c:]=0.2*(x[c:]-1)/(1-letter/M)+.6
        return x_out
    else:
        c=int(letter/M*L)
        x_out=np.zeros(np.size(x))
        x_out[:c]=0.2*x[:c]/(letter/M)+.4
        x_out[c:]=-(-0.2*(1-x[c:])/(1-letter/M))+.4
        return x_out
 
x=np.linspace(0,1,L)
for i in range(1,27):
    y=Hurst(x,i)
    plt.plot(y)
    print('----------i=============',i)
    plt.show()
